#!/usr/bin/env bash

set -x
color["focused"]="0xE0808080"

# ===== Loading Scripting Additions ============

# See: https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#macos-big-sur---automatically-load-scripting-addition-on-startup
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"


yabai -m config layout bsp
yabai -m config window_placement second_child
# yabai -m window_shadow on
# yabai -m active_window_opacity 1.0
yabai -m config active_window_border_color  "${color["focused"]}"

# yabai -m normal_window_opacity 0.90
# Padding
yabai -m config top_padding 10
yabai -m config bottom_padding 15
yabai -m config right_padding 9
yabai -m config left_padding 10
yabai -m config window_gap 10

# mouse settings
yabai -m config mouse_follows_focus on
yabai -m config mouse_modifier alt
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap

# Disable specific apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Finder$" manage=off

set +x
